# Generated by Django 5.1.1 on 2024-09-19 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "manufacturer",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("type", models.CharField(blank=True, max_length=50, null=True)),
                ("year_of_manufacture", models.IntegerField(blank=True, null=True)),
                ("engine_type", models.CharField(blank=True, max_length=50, null=True)),
                ("fuel_type", models.CharField(blank=True, max_length=50, null=True)),
                ("horsepower", models.IntegerField(blank=True, null=True)),
                ("top_speed", models.FloatField(blank=True, null=True)),
                ("seating_capacity", models.IntegerField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("length", models.FloatField(blank=True, null=True)),
                ("width", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("wheelbase", models.FloatField(blank=True, null=True)),
                ("ground_clearance", models.FloatField(blank=True, null=True)),
                ("cargo_capacity", models.FloatField(blank=True, null=True)),
                ("fuel_efficiency", models.FloatField(blank=True, null=True)),
                (
                    "emission_standard",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserVehicleInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("driven", "Driven"),
                            ("experienced", "Experienced"),
                            ("seen", "Seen"),
                            ("want_to_try", "Want to Try"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_of_interaction", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("review", models.TextField(blank=True, null=True)),
                ("photos", models.JSONField(blank=True, default=list, null=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("friends", "Friends"),
                            ("private", "Private"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.vehicle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("value", models.TextField(blank=True, null=True)),
                ("is_standard", models.BooleanField(default=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
        ),
    ]
